version: '2'

services:
  client:
    build: ./frontend
    env_file:
      - .env
    ports:
      - ${ANGULAR_PORT}:80
  server:
    build: ./backend
    env_file:
      - .env
    ports:
      - ${NODE_PORT}:8080
    depends_on:
      - database
  database:
    image: mongo
    restart: always
    ports:
     - ${MONGO_PORT}:27017